### ISSUE TITLE
Can't compile the sample code in Xcode 6.1.1

### ISSUE THREAD

**Issue by Beck-Sisyphus** [relayr/apple-sample-apps#1]
lexical or preprocessor issue 'Relayr/Relayr.h' file not found

The wunderbar API doesn't work on my Xcode neither. Might be a backward compatibility issue in Xcode.

**Comment by dehesa** [comment]
Hi @Beck-Sisyphus 

I just downloaded, compile and run repo in Xcode 6.1.1. I didn't have any problem. May I suggest the following:

* Open the workspace and not the single projects. You can later on choose the project you want to run by selecting the appropriate targets.
* Completely clean the previous compiled data by pressing ⌘+⌥+⇧+K. Alternatively, you can get the same outcome by going to the Xcode menu bar > Product > (holding ⌥) Clean Build Folder.
* Or even better, delete all the previous Xcode "Derived data" by completely quitting XCode, and deleting in finder the folder: ~/Library/Developer/Xcode/DerivedData

Let me know how it works out.

**Comment by Beck-Sisyphus** [comment]
Thanks dehesa,

I've tried all three and it doesn't work. BTW when I do 
rm -rf DerivedData
Xcode will immediately auto compile again.

The issue might be the framework setting in my computer, because I use cocoapods to manage all the framework. Hope the relayr could be on cocoapods one day!

**Comment by dehesa** [comment]
Hey @Beck-Sisyphus,

After some more investigation, some "sorrys" are due :) It seems I had some absolute paths in the sample-apps projects. I fixed it now. Sorry!

I will highly appreciate it if you can check it out again. I did check the sample apps in other computers and some other people run them. So I hope it will be fine. But you never know.

PS: There is another cool project in the sample app that I just added for this weekend Hackaton, here in Berlin (http://www.hackthehouse.io)
